name: ci
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK-17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Debug file structure
        run: ls -R

      - name: Run Tests
        run: ./mvnw clean compile test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-bot-app-report
          path: target/surefire-reports

      - name: Build Project
        run: ./mvnw package
